[package]
name = "rocket-record"
version = "0.1.0"
authors = ["李磊 <this.lilei@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rocket = "0.4"
rocket_contrib = "0.4"